# Generated by Django 5.2.15 on 2026-06-27 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('size', models.IntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('is_free', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.IntegerField(db_index=True, default=0)),
                ('path', models.CharField(max_length=700)),
                ('size', models.BigIntegerField(default=0)),
                ('block_size', models.IntegerField(default=262144)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('content_type', models.CharField(blank=True, default='', max_length=256)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('namespace', 'path')},
            },
        ),
        migrations.CreateModel(
            name='FileBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='django_fsspec.filenode')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_blocks', to='django_fsspec.storageblock')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('file', 'sequence')},
            },
        ),
    ]
