# Generated by Django 5.2.15 on 2026-06-28

import django.db.models.deletion
from django.db import migrations, models


def create_default_namespace(apps, schema_editor):
    Namespace = apps.get_model("django_fsspec", "Namespace")
    Namespace.objects.using(schema_editor.connection.alias).get_or_create(
        id=1,
        defaults={
            "name": "default",
            "description": "Default namespace",
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.BinaryField()),
                ("size", models.IntegerField(default=0)),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                ("is_free", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Namespace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.SlugField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "read_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups that can read files in this namespace.",
                        related_name="dav_read_namespaces",
                        to="auth.group",
                    ),
                ),
                (
                    "write_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups that can write files in this namespace.",
                        related_name="dav_write_namespaces",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("read_namespace", "Can read all namespaces"),
                    ("write_namespace", "Can write all namespaces"),
                ],
                "verbose_name": "Namespace",
                "verbose_name_plural": "Namespaces",
            },
        ),
        migrations.CreateModel(
            name="FileNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=700)),
                (
                    "node_type",
                    models.CharField(
                        choices=[("file", "File"), ("directory", "Directory")],
                        default="file",
                        max_length=16,
                    ),
                ),
                ("size", models.BigIntegerField(default=0)),
                ("block_size", models.IntegerField(default=32768)),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                ("content_type", models.CharField(blank=True, default="", max_length=256)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="django_fsspec.namespace",
                    ),
                ),
            ],
            options={
                "unique_together": {("namespace", "path")},
            },
        ),
        migrations.CreateModel(
            name="FileBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.IntegerField()),
                ("file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="blocks", to="django_fsspec.filenode")),
                ("block", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="file_blocks", to="django_fsspec.storageblock")),
            ],
            options={
                "ordering": ["sequence"],
                "unique_together": {("file", "sequence")},
            },
        ),
        migrations.RunPython(create_default_namespace, migrations.RunPython.noop),
    ]
