# Generated by Django 5.2.15 on 2026-06-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_fsspec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='filenode',
            name='django_fssp_namespa_361d8a_idx',
        ),
    ]
